name: Release

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release type (patch, minor, major)"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  check-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Check release permissions
        uses: actions/github-script@v7
        with:
          script: |
            const { data: repo } = await github.rest.repos.get({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            // Check if user has admin or maintain permissions
            const { data: permission } = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: context.actor
            });

            const allowedRoles = ['admin', 'maintain'];
            const userRole = permission.permission;

            console.log(`User: ${context.actor}`);
            console.log(`Permission: ${userRole}`);

            if (allowedRoles.includes(userRole)) {
              console.log('✅ User has sufficient permissions for releases');
            } else {
              core.setFailed(`❌ Insufficient permissions. Required: ${allowedRoles.join(' or ')}. Current: ${userRole}`);
            }

  check-ci:
    needs: check-permissions
    runs-on: ubuntu-latest
    outputs:
      ci-passed: ${{ steps.check.outputs.passed }}
    steps:
      - name: Check if CI passed on latest commit
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const { data: runs } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ci.yml',
              head_sha: context.sha,
              status: 'completed'
            });

            const latestRun = runs.workflow_runs[0];
            if (latestRun && latestRun.conclusion === 'success') {
              core.setOutput('passed', 'true');
              console.log('✅ CI passed on latest commit');
            } else {
              core.setOutput('passed', 'false');
              core.setFailed('❌ CI has not passed on the latest commit. Please ensure CI passes before releasing.');
            }

  release:
    needs: [check-permissions, check-ci]
    if: needs.check-ci.outputs.ci-passed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # Try to restore build artifacts from CI
      - name: Restore build artifacts from CI
        id: cache-restore
        uses: actions/cache@v4
        with:
          path: |
            dist/
            coverage/
          key: build-artifacts-${{ github.sha }}
          restore-keys: |
            build-artifacts-

      - name: Build package (CI already verified quality)
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: npm run build

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set release type
        id: release-type
        run: echo "type=${{ github.event.inputs.release-type }}" >> $GITHUB_OUTPUT

      - name: Bump version and create release notes
        id: version
        run: |
          # Get current version
          current_version=$(node -p "require('./package.json').version")
          echo "Current version: $current_version"

          # Bump version
          npm version ${{ steps.release-type.outputs.type }} --no-git-tag-version

          # Get new version
          new_version=$(node -p "require('./package.json').version")
          echo "New version: $new_version"
          echo "version=$new_version" >> $GITHUB_OUTPUT

          # Generate release notes with commit messages
          echo "## What's Changed" > release_notes.md
          echo "" >> release_notes.md

          # Add commit messages since last tag
          if git describe --tags --abbrev=0 >/dev/null 2>&1; then
            last_tag=$(git describe --tags --abbrev=0)
            git log $last_tag..HEAD --pretty=format:"* %s" >> release_notes.md
            
            echo "" >> release_notes.md
            echo "**Full Changelog**: https://github.com/${{ github.repository }}/compare/$last_tag...v$new_version" >> release_notes.md
          else
            echo "* Initial release" >> release_notes.md
          fi

      - name: Commit version bump
        run: |
          git add package.json package-lock.json
          git commit -m "chore(release): bump version to v${{ steps.version.outputs.version }}"
          git tag "v${{ steps.version.outputs.version }}"
          git push origin main
          git push origin "v${{ steps.version.outputs.version }}"

      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          body_path: release_notes.md
          draft: false
          prerelease: false
